# Redirect server (tcp46:80 -> tcp46:443)
server {
    listen 80;
    listen [::]:80;

    server_name srva.cyber.cs.unh.edu srva6.cyber.cs.unh.edu;
    return 301 https://$host$request_uri;
}

# SSL server (tcp46:443)
server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name srva.cyber.cs.unh.edu srva6.cyber.cs.unh.edu;
    root /var/www/unhcsc.github.io;
    index index.html;

    ssl_certificate /etc/letsencrypt/live/srva.cyber.cs.unh.edu/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/srva.cyber.cs.unh.edu/privkey.pem;
}